### ISSUE TITLE
Make frogs less dependant on inkscape specific effects

### ISSUE THREAD

**Issue by Miepee** [Riesi/frog_emojis#2]
The following frogs currently don't render well in anything other than inkscape:
- [x] msfrog
- [x] nvidifrog
- [x] mffrog
- [x] missingfrog
- [x] plagfrog
- [x] bifrog

**Comment by Riesi** [comment]
fixed mffrog and missingfrog
![image](https://user-images.githubusercontent.com/27691485/169023711-4931daa0-5a2d-43b7-8980-779342737822.png)

**Comment by Miepee** [comment]
the last frog, nvidifrog, got "fixed" by b0dd62244b7f0c510726d0966152d2c5cddac202
