### ISSUE TITLE
Get rid of unnecessary resolutions

### ISSUE THREAD

**Issue by Miepee** [Riesi/frog_emojis#3]
- [x] Don't seperate for width and height after #1
- [x] put everything but x72, x512 and x1024 behind a gitignore

**Comment by Riesi** [comment]
we should also:
- [ ] remove the deleted resolutions from git history
- [ ] remove the resolutions from gen_png.py
- [ ] implement custom resolutions in gen_png.py
- [ ] get rid of fixed_width/height after this and #1

**Comment by Miepee** [comment]
Has been done now. The [legacy](https://github.com/Riesi/frog_emojis/tree/legacy) branch exists, showing the repo before the resolutions were deleted from the git history.
